apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: a-openapi-spec
    description: A Python Library
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: pep8speaks-org/pep8speaks
    tags:
        - python
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: openapi
    lifecycle: production
    owner: sanjaypakale
    system: project-ddp
    defination:
      $text: https://github.com/sanjaypakale/practice/blob/master/sample.json
